### ISSUE TITLE
 Class 'Janartist\Core\Log\Log' not found

### ISSUE THREAD

**Issue by shangeyao** [janartist/hyperf-elasticsearch#2]
[ERROR] Class 'Janartist\Core\Log\Log' not found[426] in ~/vendor/janartist/elasticsearch/src/Builder.php
[ERROR] #0 ~/vendor/janartist/elasticsearch/src/Builder.php(114): Janartist\Elasticsearch\Builder->run('search', Array)
#1 ~/app/Controller/GoodsController.php(39): Janartist\Elasticsearch\Builder->get()

**Comment by jackcrafted** [comment]
new tag is publish!
